import React from 'react'
import type { Metadata } from 'next'
import { NavigationProvider } from '@/providers/NavigationProvider'

export const metadata: Metadata = {
  title: 'Hono | nextjs',
  description: 'Generated by hono',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body>
        <NavigationProvider>{children}</NavigationProvider>
      </body>
    </html>
  )
}
